### ISSUE TITLE
Ping user that dont write in english 

### ISSUE THREAD

**Issue by FurstvonMarshall** [Dougley/MBv2#104]
**Is your feature request related to a problem? Please describe.**
Some user in discord feedback dont get it that the server is english only

**Describe the solution you'd like**
ping the user with english only pls and a link to the support 

**Additional context**

**Comment by Rexogamer** [comment]
It’s **not** English only; a suggestion is valid in any language as long as it abides by the same rules as English ones.

**Comment by Rexogamer** [comment]
Also, how would they understand the messsage?

**Comment by FurstvonMarshall** [comment]
well ping them in their language

**Comment by Rexogamer** [comment]
That would take a lot of code and isn’t worth the effort as, well, it’s _not_ English only.

**Comment by Rexogamer** [comment]
Maybe this could be like a notification that it has to be a suggestion but it’d be easier to just write translated suggestion guidelines.

**Comment by FurstvonMarshall** [comment]
**it is worth an effort for all the users who  dont speak english well that is like minimodding to say english only**

**Comment by Rexogamer** [comment]
...Sorry? You were the one who claimed it was English only, but why not just write the rule so in different languages? Also, neither solution doesn’t anything about Zendesk users.

**Comment by FurstvonMarshall** [comment]
well then the rules should be written in the 14 languages and put some non english channels on the server aswell

**Comment by Rexogamer** [comment]
...that’s what I’m suggesting...
