### ISSUE TITLE
Ability to make/use Tags.

### ISSUE THREAD

**Issue by Tenpaii** [Dougley/MBv2#105]
**Is your feature request related to a problem? Please describe.**
People constantly joining the server asking for Support questions etc.

**Describe the solution you'd like**
The ability to make or at least use Tags. Think Etiket from DDevs. Would be nice if GVs could be given the perk to make Tags and require 5+ votes from other Custodians to implement the tag but if not, just leave it up to the mods to make tags.

This would also mean it's time for MegaBot to finally have access to #feedback-discussion once again since IIRC the reason it was hidden for him in the first place was so people wouldn't randomly get Custodian from streaks from the messages there.

**Additional context**

**Comment by Dougley** [comment]
GearBoat already has this, won't be adding this to MegaBot
