### ISSUE TITLE
Show suggestion IDs when you use !search.

### ISSUE THREAD

**Issue by Tenpaii** [Dougley/MBv2#106]
**Is your feature request related to a problem? Please describe.**
Makes it easier to info a suggestion you're searching for when you're on mobile instead of having to open the browser.

**Describe the solution you'd like**
Show the corresponding suggestion ID on the field right next to the suggestion.

**Additional context**

**Comment by Dougley** [comment]
Implemented since https://github.com/Dougley/MBv2/commit/dcf8b34f7aa4680d81c04e752b3b5fd3cd5eeb89
