### ISSUE TITLE
Full Results

### ISSUE THREAD

**Issue by Benricheson101** [Dougley/MBv2#119]
## Preface: I'm using the search terms "gift card" as an example. It is reproducible with other terms, but I know that results show up when searching for gift cards

**Describe the bug**
If you search for something with a space, it will put `gift%20card` in the search bar (not URL bar)
**To Reproduce**
1. `!search gift card`
2. Click full results
3. It will say `gift%20card` and have 0 results

**Expected behavior**
Searches for `gift cards`, shows correct results 
**Screenshots**
[Link to Screenshots](https://photos.app.goo.gl/ccFrmf78XeBKFb8P8) The first picture is the actual result, and the second is the expected one.

**Additional context**
I like the feature! It will be very helpful for mobile users!

**Comment by MoonlightCapital** [comment]
Cannot reproduce. My browser (Firefox) automatically decodes the character into a space and the search continues like fine.

**Comment by Benricheson101** [comment]
Upon further testing I found that it’s only broken on my phone, so it’s probably a ZD issue and not a MB issue.
