### ISSUE TITLE
Be able to dupe more than one suggestion into the same master in one command.

### ISSUE THREAD

**Issue by spudpotato** [Dougley/MBv2#121]
**What's your feature request about?**
For there to be a way to merge two dupes in to one master in a single !dupe command.

**Is your feature request related to a problem you're having? Please describe.**
Sometimes I find two duplicates that both have the same master. It would be handy if I could just merge them both in to the master in one command. 

**Describe the solution you'd like**
For there to be a way to merge more than one suggestion in to the same master, with part of the command clearly separating the dupes and the master.

**Comment by MoonlightCapital** [comment]
Yes pleeeeeeeeease, i've been wanting this for months and now it's just a must-have.

**Comment by username-6** [comment]
That would be SO nice! Maybe it could be something like `!dupe <Dupe 1> <Dupe 2>... | <Master>`.

**Comment by Rexogamer** [comment]
I’d do it how @username-6 suggested.

**Comment by MoonlightCapital** [comment]
Is the `|` really needed? getting the last argument and treating like the last ticket would work better.
