### ISSUE TITLE
Silently fail bulk dupe errors

### ISSUE THREAD

**Issue by MoonlightCapital** [Dougley/MBv2#126]
**What's your feature request about?**
> Recently, the dupe command has received an update that made it accept multiple suggestions at once, and then merge them all into a single one

**Is your feature request related to a problem you're having? Please describe.**
> I'm always frustrated when I find some old dupe on the site, or another custodian beat me to the punch for **any** of the suggestions I want to dupe. If any suggestion is marked as answered or already duped, the bot will just give a vague message that tells me that, so I have to scan every suggestion I put in to remove the unacceptable ones.

**Describe the solution you'd like**
> Filter out answered and already duped suggestions from the command, and if nothing can be dupe, throw an error.

**Comment by Kitty-Therapist** [comment]
This should have been sorted out in #138.
