### ISSUE TITLE
Error message for dupe request already existing is wrong

### ISSUE THREAD

**Issue by thedarthonian** [Dougley/MBv2#136]
**Describe the bug**
When a dupe request is already pending for a suggestion, it gives the message _Some of your dupes are already being merged_ instead of 'This dupe is already being handled'

**To Reproduce**
1. Try to dupe these two suggestions `!dupe https://support.discordapp.com/hc/en-us/community/posts/360044114471--Suggestion-Server-Owners-should-have-the-option-to-disable-boosting-if-they-want https://support.discordapp.com/hc/en-us/community/posts/360044835652-Possible-to-turn-the-new-boosting-feature-off-for-our-server-`

**Expected behavior**
It should state that a dupe request is already pending

**Screenshots**
https://i.imgur.com/gMhry2O.png

**Additional context**
I know this is not down to my dupe already being processed, as I haven't submitted one weeks before this.

**Comment by spudpotato** [comment]
This is the same as the feature request #126
