### ISSUE TITLE
Blocking Discord Invites

### ISSUE THREAD

**Issue by blastoise186** [Dougley/MBv2#24]
**Is your feature request related to a problem? Please describe.**
There's a fair few Discord Invites on Zendesk which have been posted since the transfer from UserVoice. I have a suspicion that someone might abuse the system to advertise their server while bypassing GearBoat.

**Describe the solution you'd like**
One thing that might help is to make sure MegaBot does not send Discord Invites from Discord Feedback to Zendesk, nor post them back from Zendesk to Discord Feedback.

It would also be cool if any new Suggestions that appear to contain Discord Invites are automatically deleted from the live feed in DFeedback and get immediately flagged for Admin review.

**Describe alternatives you've considered**
GearBoat is capable of deleting unauthorised invites posted in DFeedback,but is unable to handle anything related to MegaBot, so it might need to be added this side. Also, it may be useful to have a backup filter in case GearBot is unable to catch an invite before MegaBot does.

**Additional context**
Nothing of note

**Comment by blastoise186** [comment]
Thanks @AEnterprise , that sounds like a good option to me as I'm assuming that GearBoat would also pick up on Bot Commands which may have disallowed content.

I also think that having an extra safety net of scanning for any Discord Invites within MegaBot during the command processing might be a good thing in case GearBoat is down or failed to act for some reason. 

I probably wouldn't want MegaBot to become some kind of ModBot, so diverting anything it picks up on to Mod/Admin review before sending to Zendesk might be an option. Do you think having safety nets like these on both Bots would be workable?

Also, given that Bots shouldn't generally react to each other, it makes sense that MegaBot and GearBoat each disregard the others messages, so having the ability for MegaBot to strip out Discord Invites while retaining the rest of the content when commands like !info are used might also help.

Thanks!

**Comment by AEnterprise** [comment]
GearBoat doesn't care about the rest of the content, if it has things that are not allowed it's removed, plain and simple

it does log things to a logging channel so i guess megabot could pick up on that as well? though that only logs 'this got deleted', so megabot will either have to filter out those out himself (as there could be multiple) or just ignore/refuse it when it gets removed by gearboat

**Comment by AEnterprise** [comment]
yeah the context is submitting feedback, like people using the submit commands but the feedback has an invite or blacklisted insults in it

**Comment by blastoise186** [comment]
That's right, but also in cases where MegaBot might pull down with a suggestion or comment coming back from Zendesk, might warrant a filter to prevent commands such as !info posting invites.
