### ISSUE TITLE
Shouldn't it be MBv3?

### ISSUE THREAD

**Issue by reckr** [Dougley/MBv2#25]
Hi there,

I noticed that MegaBot is in its third version, 3.1.0. Maybe this repo name, the description, and the README should be updated?

Just a suggestion!
Kind regards,
Casper.

**Comment by reckr** [comment]
I just saw that the latest release indeed is 2.0.1, sorry!

**Comment by Dougley** [comment]
Technically yes, but renaming a repository can have unforeseen circumstances.
