### ISSUE TITLE
Some general ideas to improve self-moderation between Custodians

### ISSUE THREAD

**Issue by SuperSajuuk** [Dougley/MBv2#27]
Last night, it became clear there are some issues with reporting feedback posts and a lack of being able to self-moderate each other. By self-moderating, I mean that Custodians should be able to decide the outcome of something without needing to call mods/Dabbit at every possible chance to resolve issues.

So I came up with a workflow like this when it comes to reporting feedback messages:

- Increase the number of report reactions from Custodians. The amount should be randomly selected between either 4-8, to make things less predictable and increase accuracy of reporting tickets. The variance can be determined by the number of +1 or -1 reactions already on the report (so more reports needed for a feedback post containing lots of +1's, less reports needed for a post containing a lot of -1's etc

- When the report count is reached, the bot should decide whether it wants to randomly poll some of the Custodians who reported the feedback post. This can be anywhere from 0 custodians (so nobody) to 50% of the custodians who have reported this post. If it decides to ask for feedback from Custodians, the bot DM's those it has selected and asks them to reply with a reason why they reported the post.

- Once those Custodians have feedbacked in this way, the bot posts into a Custodians Only feed channel like "Reported Feedback Feed", with a message that looks something like this: 
```
:reported: X custodians have reported the following feedback post: link-to-post-here

A random selection of Custodians were asked for verification, the following reasons were given:
- list
- of
- reasons
- here
```
For fairly obvious reasons, the names of who gave this feedback is not revealed to Custodians, but this would be visible to the mods/Dabbit. If Custodians don't agree with the reasons given, a discussion can be had in custodian-central and if those who reported no longer agree it should be reported, they can rescind their report and remove it from queue.

I genuinely feel this would help to reduce the level of arguments, promote trust with each other and reduce the amount of reports being sent to the Admin queue, therefore reducing Dabbit's workload.

**Comment by Dougley** [comment]
The system we have currently is in-spec with what Dabbit wanted. I ran this by him and the intention for the report system to be heavily based on admin oversight is intended behavior. If you have issues with this I suggest you contact Dabbit instead.
