### ISSUE TITLE
Ability to revoke a vote

### ISSUE THREAD

**Issue by Thereatra** [Dougley/MBv2#31]
**Is your feature request related to a problem? Please describe.**
Currently if you missclick and vote on the wrong thing or change your mind there's no way to revoke it without using the website.

**Describe the solution you'd like**
The ability to revoke a vote on a suggestion when removing the reaction.

**Describe alternatives you've considered**
This could also be achieved by having a `!revoke` command or by using the `!vote` command again on a suggestion.

**Comment by Dougley** [comment]
Returning to a neutral state when reactions are removed is definitely possible.
However, we currently don't listen to reactionRemove for performance sake (same reason as of why we don't listen to guildMemberUpdate anymore for welcoming)
