### ISSUE TITLE
Strikethrough already bought roles in the store

### ISSUE THREAD

**Issue by Thereatra** [Dougley/MBv2#34]
**Is your feature request related to a problem? Please describe.**
Since you can't buy roles you already have it should clearly show so

**Describe the solution you'd like**
**1**: ~~Record Keeper - 350 EXP~~
**2**: ~~Book Keeper - 750 EXP~~
**3**: Librarian - 1500 EXP
If you already have the role.

**Comment by Dougley** [comment]
Implemented since 9bc28bcee3b67990553d287f0ab359f4dcde0915
