### ISSUE TITLE
The ability to self-cancel accidental Dupe Requests

### ISSUE THREAD

**Issue by blastoise186** [Dougley/MBv2#36]
**Is your feature request related to a problem? Please describe.**

Sometimes we make mistakes like accidentally Dupe Requesting unrelated suggestions or getting the Dupe/Target mixed up. Currently the only way to fix this is to ask Dabbit to Deny the request and re-submit, which can take a while.

**Describe the solution you'd like**

It would be really great to have some kind of `!canceldupe` command that would let us self-cancel an unintended/accidental dupe request and remove it from the queue instantly, without having to wait for Dabbit to release the deadlock. I could just do `!canceldupe 123456 654321` and MegaBot would automatically pull the request from the Admin Queue so that I can retry with the intended requests.

**Describe alternatives you've considered**

At the moment, the only kind of self-cancel is to ask Dabbit to manually Deny a Dupe Request, which leaves it deadlocked - in some cases this could be for several days.

**Additional context**

The only effect in terms of EXP that I'd like to see from the usage of `!canceldupe` is that the Pending EXP from the request is reverted, but otherwise making the command free to use. Also, this could help to cleanup the Admin Queue and allow Dabbit to focus on reports which need attention, therefore making it faster for him to process them.

**Comment by blastoise186** [comment]
I had a chat with several Custodians and Ghoul this evening and there was strong support for this idea. Sorry I forgot to note this!

**Comment by Devilxdd** [comment]
i support this idea
- Super#8276

**Comment by blastoise186** [comment]
Thanks Dougley, it's already a great help
