### ISSUE TITLE
Force Reporting for invalid suggestions

### ISSUE THREAD

**Issue by blastoise186** [Dougley/MBv2#38]
**Is your feature request related to a problem? Please describe.**

There are some suggestions which get posted to the site which are not only invalid, but also need to be removed from public view as quickly as possible for one reason or another. It's not appropriate to give examples in this Issue, however they are ones that we know shouldn't be posted on the feedback site at all. Dabbit isn't always available, so while we can remove them from DFeedback, they remain visible on the feedback site since we can't do anything about them right now until Dabbit checks in.

This isn't ideal for reported suggestions that may have privacy or safety issues, since anyone can see them before Dabbit can respond.

**Describe the solution you'd like**

After a discussion between several Custodians this evening, we all agreed that a possible ModOnly `!force-report` command would be useful. The idea behind this would be that if a particular Suggestion needs to be swiftly handled but Dabbit isn't available, we can ask a Mod to force a report through which hides the Suggestion on both the site and server from public view until Dabbit is able to properly review it. In the event that any Custodians used the regular Report command before a Mod used force-report, they should still be able to have their EXP handled via the usual process.

To prevent abuse, the force-report command itself should be ModOnly.

Zendesk makes it possible to Unpublish content without fully Deleting it, so that feature might be one way to handle this because content can still be re-published or deleted later - this could be used as a sort of quarantine area where force-reported suggestions could be held back.

The idea of this is to provide a "best of both worlds" approach between rapidly taking down suggestions that need emergency attention whilst also allowing Dabbit to review them once he's available.

**Describe alternatives you've considered**

Currently, we can request a Mod to remove them from the feed and we can try to contact Dabbit and ask for an immediate review, but it's not always possible for the Mods or Dabbit to handle them quickly.

**Additional context**

This feature request has been submitted following a discussion between myself, MoonlightCapital, Jojo, Super, Joni, Thunder33345 and jedi3 this evening in which we discussed and drafted the idea together.

The intention is that force-report should only be used for suggestions which need urgent attention, not for general reports.

**Comment by Superie** [comment]
i agree

**Comment by Dougley** [comment]
@Superie Please use reactions instead

**Comment by Dougley** [comment]
This isn't possible in the way you describe it, the endpoint to hide content only applies to articles and not to posts, posts can only be deleted (types matter!).   
I'm also not adding a way for posts to be forcefully added to the queue, this undermines the integrity of the reporting system as a whole. A way for mods+ to delete suggestions outside of the queue will also not be added.
