### ISSUE TITLE
Require the roles to be bought in order from lowest->highest

### ISSUE THREAD

**Issue by Thereatra** [Dougley/MBv2#43]
**Is your feature request related to a problem? Please describe.**
As I see it the roles _(in order)_ should be an indication of how much you have contributed as a Custodian, therefor it does not make sense that you can buy the highest role without having the preceding ones.

**Describe the solution you'd like**
Require the roles to be bought in order from lowest->highest. This would up the total exp requirement for Grand Vizier to 9770 exp _(without counting the Custodian role itself)_, which I think better reflects it being the highest role.

**Describe alternatives you've considered**
A possible additional requirement for roles could be a certain amount of dupes, reports etc. This would essentially just be an activity indication requirement.

**Additional context**
I think the current requirements for getting the highest role _(Grand Vizier)_ is too low. As I see it the roles should be an indication of how much you have contributed as a Custodian, therefor I think the Grand Vizier role should show that the Custodian have actively contributed a lot. 

Here's a breakdown of how a Custodian could go about getting Grand Vizier with the current requirements, I assume that the Custodian does a little bit of everything.
- 80 Logins: 2000 exp
- 100 Dupes: 2000 exp
- 110 Reports: 550 exp
- 20 Comments: 100 exp
- 50 Votes: 100 exp
- 2 Suggestions: 20 exp
This means that Grand Vizier would be obtainable in ~80 days with little daily work and no events, and if done in the same time as with the streak system _(120 days)_ with ~36% less actions due to the extra login exp.

Here's a breakdown of how a Custodian could go about getting Grand Vizier with the new exp requirements, again I assume that the Custodian does a little bit of everything.
- 100 Logins: 2500 exp
- 275 Dupes: 5500 exp
- 270 Reports: 1350 exp
- 40 Comments: 200 exp
- 100 Votes: 200 exp
- 2 Suggestions: 20 exp
This means that Grand Vizier would be obtainable in ~100 days moderate daily work and no events, and if done in the same time as with the streak system _(120 days)_ with ~5% less actions due to the extra login exp.

It's worth to keep in mind that a lot of the actions like reports will happen dynamically if the Custodian is active on the server anyway.

**Comment by Dougley** [comment]
Issues regarding the rewards in the EXP system should go to Dabbit, I'm going to mark this as wontfix for the time being while I relay this to him. You'll hear from me later :smiley:

**Comment by Dougley** [comment]
Implemented since 9bc28bcee3b67990553d287f0ab359f4dcde0915
