### ISSUE TITLE
Add command to mark suggestions containing multiple ideas

### ISSUE THREAD

**Issue by Thereatra** [Dougley/MBv2#47]
**Is your feature request related to a problem? Please describe.**
Sometimes people make suggestions that contain [multiple ideas](https://support.discordapp.com/hc/en-us/community/posts/360030104492) which isn't very useful feedback wise.

**Describe the solution you'd like**
Add a `!multi <id>` command that marks the suggestion for admin action.
The perfect scenario would be the ability to automatically split up the ideas in the suggestion and resubmit them as individual suggestions. 
Since that is in no way easy or maybe even possible, I suggest some sort of admin quick-response requesting that the user resubmit their feedback with the ideas split up in to individual suggestions.

**Comment by Dougley** [comment]
This is tricky, I don't see how I can split the suggestion automatically (and I don't want it to be manual)
If we drop the splitting part we basically create a new type of reporting, since asking them to resubmit has the same effect as closing it as inappropriate.

**Comment by Thereatra** [comment]
Hadn't really thought about it that way, but you're totally right it would end up just being a new type of report. I guess adding multi suggestions to the list of things that can be reported would give the same result then 🤔
