### ISSUE TITLE
MetaBot Mistaken

### ISSUE THREAD

**Issue by NoahDiscord** [Dougley/MBv2#52]
**Describe the bug**
MegaBot responded this: "The category you provided is incorrect, please see #helpful-resources for a list of valid categories" I'm not sure if bot means that should be a custodian channel or #bot-instructions
**To Reproduce**

1. Type a command that doesn't exist for example !store

**Expected behavior**
Should show me a correct channel

**Screenshots**
https://imgur.com/a/ySY2Vxj

**Comment by Dougley** [comment]
This is marginally intended, when the store system was created it was intended for custodians only, so store categories are in a custodian only channel.
