### ISSUE TITLE
Leaderboard should record all XP earned, even that lost to caps.

### ISSUE THREAD

**Issue by Zacatero** [Dougley/MBv2#65]
**Is your feature request related to a problem? Please describe.**
Nah, Just an idea I had

**Describe the solution you'd like**
I think the leaderboard should take into account earned XP that was lost to caps. Like if I get 50 dupes approved, but even if only 20 of them end up counting toward my spendable XP, I think the leaderboard should count all 50. 

**Additional context**
N/A

**Comment by Dougley** [comment]
The leaderboard reflects the EXP you've actually got.
If this would reflect the EXP you potentially could've gained, some people would stay at the top of the leaderboard each month - which monthly leaderboards is trying to prevent.
Also, the caps are there for a reason, circumventing them to give you a false sense of 🥇 pride and accomplishment 🥇  is wrong.
