### ISSUE TITLE
Command and Queue specifically for negative/positive feedback that IS NOT a suggestion or idea

### ISSUE THREAD

**Issue by Zacatero** [Dougley/MBv2#66]
**Is your feature request related to a problem? Please describe.**
We get a lot of submissions that are "technically" valid feedback, yet are not actual ideas or suggestions. Like positive or negative feedback about Discord or features within Discord without actually suggesting something new or a change. 

**Describe the solution you'd like**
A new command to simply put them into a queue to close the threads down. If they are valid and within the rules, we still should have a way to close them down since those submissions don't need to have comments or votes

**Additional context**
Could be something like !close

**Comment by Dougley** [comment]
This is edge case.
Zendesk is meant for both feedback - positive and negative, and suggestions. When we had UV it was suggestions only. 
If a suggestion is unreasonably hostile you should report it using the regular reporting flow.
