### ISSUE TITLE
Dupe embed like the Comment embed

### ISSUE THREAD

**Issue by drdrjojo** [Dougley/MBv2#70]
**Is your feature request related to a problem? Please describe.**
Sometimes users delete their !dupe command and you can't see anymore who requested it.
So you can't contact the requester in case the request got the wrong target.
Another reason is the channel and search results would look a little bit cleaner.

**Describe the solution you'd like**
After the !dupe command has been submitted, the initial command should be deleted like with !comment. The embed could look like this:
> **||Jojo|| submitted following dupe request:**
> Dupe: ...
> Target ...

**Additional context**
Atm, if you are searching for an suggestion id the result shows up the feed, command and the embed, this would be reduced to the feed and embed.

**Comment by drdrjojo** [comment]
Why has it been closed?

**Comment by Dougley** [comment]
It's implemented since https://github.com/Dougley/MBv2/commit/45344191b2e1d3594031fb7e0324fa289f1be86a

**Comment by drdrjojo** [comment]
This feature request has nothing to do with the !revoke request ...

**Comment by Dougley** [comment]
What? Are you sure you checked the commit I referenced? If it truly doesn't match your request feel free to reopen the issue

**Comment by drdrjojo** [comment]
Yes i checked the commit.

Reopened it with #81
