### ISSUE TITLE
Create a !latest command

### ISSUE THREAD

**Issue by blastoise186** [Dougley/MBv2#71]
**Is your feature request related to a problem? Please describe.**
There can be times when I want to pull up the details for the latest suggestion rapidly, such as if a user just posted a new suggestion and wanted to see that it has been fully posted, or if the feed can't be accessed for some reason. It's a bit slow to grab the ID just to run !info on the latest post.

**Describe the solution you'd like**
Having a command such as !latest would be useful in cases where we might want to quickly pull up the details for the most recent post as a shortcut for !info newestidinfeed. This would make it much faster to grab the details without switching channels several times - especially useful on Mobile or for users who prefer to only use the keyboard as much as possible.

**Additional context**
A discussion was started in the server following a comment on #69 , I'm opening an Issue here for tracking and to keep the discussion easy to locate.

**Comment by Dougley** [comment]
Implemented since https://github.com/Dougley/MBv2/commit/874d6dac16cba1c876a2b077e3a10710384f538d
