### ISSUE TITLE
Report reaction still appears if you send a link

### ISSUE THREAD

**Issue by zSnails** [Dougley/MBv2#78]
**Describe the bug**
Report reaction still shows if you send a link in the custodian channel,

**To Reproduce**
1. Go to the latest submission in the feedback channel 
2. Copy a submission link
3. Send it in the custodian channel
4. See how MB still adds the :report: reaction to it

**Expected behavior**
The :report: emote shouldn't show
**Screenshots**
https://i.imgur.com/qOfkiQc.png

**Comment by Tarek1337** [comment]
According to this https://github.com/Dougley/MBv2/issues/77, it seems intentional

**Comment by MoonlightCapital** [comment]
Intended. The report reaction was only removed from feed so the Custodians would post a link in #custodian-central and discuss whether it should be reported or not.

**Comment by Dougley** [comment]
Intended behaviour
