### ISSUE TITLE
!dog and !cat command bugged

### ISSUE THREAD

**Issue by drdrjojo** [Dougley/MBv2#80]
**Describe the bug**
Sometimes the !dog or !cat command only shows a fact without picture.

**To Reproduce**
1. Use !dog
2. See error 
3. No error? Try step 1-2 again

**Expected behavior**
Picture and a fact should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/5618447/54740479-d2da4c00-4bbb-11e9-986f-6ff8d22096f8.png)

**Additional context**
!penguin

**Comment by Dougley** [comment]
!dog was using wrong selectors, this is fixed in dev
!cat is just really slow and there's not much I can do about that
