### ISSUE TITLE
Add the :reported: emote when the suggestion is reported

### ISSUE THREAD

**Issue by ZXslash** [Dougley/MBv2#82]
**Is your feature request related to a problem? Please describe.**

I understand that you removed the :report: reaction, but I would like to know if a suggestion has been reported before I go ahead and copy the link

**Describe the solution you'd like**

Just simply add the :reported: reaction if a suggestion has been reported in \#new-suggestion-feed

**Additional context**

**Comment by spudpotato** [comment]
Yeh, this would be extremely useful. It's annoying having to do !info just to see if a suggestion has been reported.
