### ISSUE TITLE
Spacing between dupe and the first id

### ISSUE THREAD

**Issue by FurstvonMarshall** [Dougley/MBv2#84]
When I dupe I dont see the blank space behind the dupe command as megabot says no input was found 

enable megabot to accept two blank spaces  after the dupe command 

A4ex

**Comment by Dougley** [comment]
I don't understand what this is about, care to elaborate?

**Comment by MoonlightCapital** [comment]
Basically multiple spaces between command arguments (such as dupe) are treated as different arguments. I've experienced this issue as well, and all I can say is that it should be fixed because i'm lazy :kappalul:

**Comment by spudpotato** [comment]
What would be the point in making so you can put two spaces? It's not hard to just delete the other space.
