### ISSUE TITLE
Increase the amount of report reactions

### ISSUE THREAD

**Issue by SuperSajuuk** [Dougley/MBv2#85]
**Is your feature request related to a problem? Please describe.**
When MegaBot was designed, the :report: reaction count was 3, because the amount of custodians that were often active at the time was very low (usually no more than 20 people had the role) due to streaks system and auto demote. That meant 3 reactions were usually enough because there wasn't a lot of custodians and the community was much smaller.

However, at the time of writing, there are well over 100 custodians. 3 reactions is way too small for such a large number of users, especially as there are a lot more active members in the group now. By having such a small number, it encourages quick reporting without enough oversight or validation of the feedback post as to whether it should be reported.

**Describe the solution you'd like**
There are two potential solutions that I can see:

1. The most obvious solution is to just increase the number of required :report: reactions before the post is sent to the admin queue for verification. I would say that anywhere between 6-8 reports is a good ballpark figure for the amount of active custodians.

2. Another solution could be to make the required amount of reports more "dynamic". By this, the bot would count the number of Custodians online at the point the reactions are added and then take a percentile value of that (rounded to a whole number, maybe 8-10%?) and consider that as the "required value". To avoid low value numbers, there would need to be a "minimum" number that is used if the %age value is less than or equal to this number (so if the minimum is 10, for example, and the %age determines that it's 8, then 10 should be used).

So for example, let's say there are 100 custodians online, and a Custodian posts a link for a feedback post to be reported. Using the second suggestion, this would require 10 custodians to use the :report: reaction for it to go to admin queue. A second example could be 120 custodians, thus requiring 12 custodians to react.

This provides more than ample time for someone to question the decision and for reactions to be removed before it goes to the queue. With the current system, 3 custodians can rapidly add a reaction without considering the context or whether it needs to be reported, and there would be no way to undo that queued item because of it.

**Additional context**
See above. All I'll say is that this should not be shot into the ground because one or two people don't like it, most people agree the reaction count is too low and needs to be increased in some way, so this is a thread to facilitate this kind of change.

**Comment by Dougley** [comment]
Solution 1 is straightforward, probably the most effective, and is the easiest to implement. The report threshold is just a constant.
Solution 2 seems convoluted, custodians being online does not imply them being active in the server, and what if there's only 1 person considered "active" at any point?

**Comment by SuperSajuuk** [comment]
I agree that with Solution 2, there is no guarantee they would be online and it is a little more complex, but it would scale with custodian totals so would not need as much editing every time this subject will end up being broached.

I don't know what library is used for MegaBot though, would it not be possible to get the role, then just check the status of each member in said role? You could then aggregate the number of "online" users and then make a percentile number out of that, if that simplified things.

With Sol2, there would be a minimum number (well I'd expect one at least, i'll edit it into my post) so if the percentage value is less than or equal to the minimum, then the minimum is used (maybe Sol1's minimum?).

**Comment by Dougley** [comment]
I've decided to increase the report threshold to 5 as a test, this issue will function as a discussion from this point forward.

**Comment by Dougley** [comment]
This experiment is considered successful.
