### ISSUE TITLE
Moderator report override 

### ISSUE THREAD

**Issue by Zacatero** [Dougley/MBv2#89]
**Is your feature request related to a problem? Please describe.**
While I agree with the 6 reports needed change, Sometimes 6 arent around and the conversation will push the embed and reactions far up

**Describe the solution you'd like**
If a mod reports, then it pushes it 100% through without needing 6. Either voting with a special command or just with the reaction

**Additional context**

**Comment by Dougley** [comment]
I feel like having people circumvent the regular reporting flow would undermine the integrity of the system, but I also understand the issue you're trying to convey.
I'll discuss this with the others.

**Comment by Dougley** [comment]
Decided that having a "super-report" undermines the system too heavily, won't be implementing this.
