### ISSUE TITLE
Be able to get someone else's stats by doing !stats <users name>

### ISSUE THREAD

**Issue by spudpotato** [Dougley/MBv2#94]
**Is your feature request related to a problem? Please describe.**
It's kinda annoying if you want to see someone's else's stats, or compare your stats, that you have to ask someone else for a screenshot of theirs. 

**Describe the solution you'd like**
To be able to do ```!stats <users name>``` in the bots DM, so you can quickly and easily see the users stats.

**Additional context**
Maybe it would be a good idea if when the user earnt the XP, and what they earnt it from, wasn't included. Also maybe have a different coloured border around the edge, so there is no way you can mix it up with your own stats.

**Comment by Dougley** [comment]
Other people's stats are considered private, you should ask them to show it to you instead.
