### ISSUE TITLE
!checkdupe command

### ISSUE THREAD

**Issue by Shadow-T-M** [Dougley/MBv2#96]
**Is your feature request related to a problem? Please describe.**
It is always frustrating to go searching for a dupe only to input it into the command and get a response saying that a dupe has already been submitted.

**Describe the solution you'd like**
Some sort of command that could check if a dupe request has already been submitted on the post (and maybe information about the ticket it's being duped into)

**Additional context**
owo shenanigans

**Comment by Dougley** [comment]
Implementing this as a separate command gets convoluted, I'm going to add this as part of the `!info` embed.
